name: Python package

# We may not want to run this on release but rather
# take the artifact from the dev build and copy/push/promote
# it to wherever production needs to go. You know don't
# build it again type of thing if it's working in dev
on: [
    pull_request,
    release
  ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    # FOR DEMO PURPOSE CHANGE SOMETHING
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # some sort of liniting like flake8 or pylint
        echo "do some linting later"
    - name: Test with pytest
      run: |
        pytest -v