name: Build and Package

on:
  workflow_call:
    inputs:
      GCP_ARTIFACT_REGISTRY:
        required: false
        type: string
        default: 'oci://us-central1-docker.pkg.dev/cyderes-dev/cyderes-helm-repo'
      APP_VERSION:
        required: false
        type: string
        default: "latest"
      HELM_PUSH:
        required: false
        type: string
        default: 'false'
    secrets:
      GCP_ARGO_SERVICE_ACCOUNT:
        required: true

jobs:
  check-chart-diffs:
    name: Check for Helm chart changes
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
      name: Checkout current branch
      with:
        fetch-depth: 0
    - name: Print env
      run: env
    - name: Check for git diffs
      id: chart-changes
      run: |
        if [[ -n "$(git --no-pager diff --name-only origin/${GITHUB_BASE_REF} -- charts | tr -d '\n\r')" ]]; then
          echo "diff detected, proceeding with version compare"
          echo "::set-output name=CHART_CHANGES::true"
          echo "::set-output name=CHART_NAME::$(cat $(find charts | grep Chart.yaml) | grep -E '^name:' | awk '{print $2}' | tr -d '\n\r')"
          echo "::set-output name=CHART_VERSION::$(cat $(find charts | grep Chart.yaml) | grep -E '^version:' | awk '{print $2}' | tr -d '\n\r')"
        else
          echo "no diff, skipping package"
          pwd
          ls -la
          git --no-pager diff charts
        fi
    outputs:
      chart_changes: ${{ steps.chart-changes.outputs.CHART_CHANGES }}
      chart_name: ${{ steps.chart-changes.outputs.CHART_NAME }}
      chart_version: ${{ steps.chart-changes.outputs.CHART_VERSION }}
  check-chart-versions:
    name: Check Helm chart version
    needs:
      - check-chart-diffs
    if: |
      always() &&
      contains(needs.check-chart-diffs.outputs.chart_changes, 'true')
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
      name: Checkout main
      with:
        ref: "main"
    - name: Check main chart version
      run: echo "PROD_CHART_VERSION=$(cat $(find charts/${{ needs.check-chart-diffs.outputs.chart_name }} | grep Chart.yaml) | grep -E '^version:' | awk '{print $2}' | tr -d '\n\r')" >> $GITHUB_ENV
    - name: Compare chart versions
      id: chart-compare
      run: |
        function version_gt() { test "$(echo "$@" | tr " " "\n" | sort -V | head -n 1)" != "$1"; }
        if [[ -z "${{ env.PROD_CHART_VERSION }}" ]]; then
          echo "WARNING: No previous chart version found, proceeding anyway"
          echo "::set-output name=PACKAGE_CHARTS::true"
        elif version_gt ${{ needs.check-chart-diffs.outputs.chart_version }} ${{ env.PROD_CHART_VERSION }}; then
          echo "${{ needs.check-chart-diffs.outputs.chart_version }} is greater than ${{ env.PROD_CHART_VERSION }}"
          echo "::set-output name=PACKAGE_CHARTS::true"
        else
          echo "Chart semantic version in pull request must be greater than main branch!"
          exit 1
        fi
    outputs:
      package-charts: ${{ steps.chart-compare.outputs.PACKAGE_CHARTS }}
  package-chart:
    name: Package and push Helm chart
    needs:
      - check-chart-diffs
      - check-chart-versions
    if: |
      (contains(needs.check-chart-versions.outputs.package-charts, 'true') || contains(github.event_name, 'release') ) && contains(inputs.HELM_PUSH, 'true')
    runs-on: self-hosted
    steps:
    - name: Pull chart repo
      uses: actions/checkout@master
    - name: Push Helm chart to Artifact Registry
      uses: FishtechCSOC/.github/.github/actions/helm-push@main
      with:
        useOCIRegistry: true
        username: '_json_key_base64'
        password: ${{ secrets.GCP_ARGO_SERVICE_ACCOUNT }}
        access-token: ${{ secrets.GCP_ARGO_SERVICE_ACCOUNT }}
        registry-url: ${{ inputs.GCP_ARTIFACT_REGISTRY }}
        force: true
        chart-folder: charts/${{ needs.check-chart-diffs.outputs.chart_name }}
        version: ${{ needs.check-chart-diffs.outputs.chart_version }}
        appVersion: ${{ inputs.APP_VERSION }}
