name: Helm Checks

on:
  workflow_call:

jobs:

  check-chart-diffs:
    name: Check for chart changes
    runs-on: self-hosted
    steps:

    - uses: actions/checkout@master
      name: Checkout current branch
      with:
        fetch-depth: 0

    - name: Check for git diffs
      id: chart-changes
      run: |
        if [[ -n "$(git --no-pager diff --name-only origin/${GITHUB_BASE_REF} -- charts | tr -d '\n\r')" ]]; then
          echo "diff detected, proceeding with version compare"
          echo "::set-output name=CHART_CHANGES::true"
          echo "::set-output name=CHART_NAME::$(cat $(find charts | grep Chart.yaml) | grep -E '^name:' | awk '{print $2}' | tr -d '\n\r')"
          echo "::set-output name=CHART_VERSION::$(cat $(find charts | grep Chart.yaml) | grep -E '^version:' | awk '{print $2}' | tr -d '\n\r')"
        else
          echo "no diff, skipping version compare"
          pwd
          ls -la
          git --no-pager diff charts
        fi

    outputs:
      chart_changes: ${{ steps.chart-changes.outputs.CHART_CHANGES }}
      chart_name: ${{ steps.chart-changes.outputs.CHART_NAME }}
      chart_version: ${{ steps.chart-changes.outputs.CHART_VERSION }}

  check-chart-version:
    name: Check chart version
    needs:
      - check-chart-diffs
    if: |
      always() &&
      contains(needs.check-chart-diffs.outputs.chart_changes, 'true')
    runs-on: self-hosted
    steps:

    - uses: actions/checkout@master
      name: Checkout main
      with:
        ref: "main"

    - name: Check main chart version
      run: |
        echo "PROD_CHART_VERSION=$(cat $(find charts/${{ needs.check-chart-diffs.outputs.chart_name }} | grep Chart.yaml) \
        | grep -E '^version:' \
        | awk '{print $2}' \
        | tr -d '\n\r')" \
        >> $GITHUB_ENV

    - name: Compare chart versions
      id: chart-compare
      run: |
        function version_gt() { test "$(echo "$@" | tr " " "\n" | sort -V | head -n 1)" != "$1"; }
        if [[ -z "${{ env.PROD_CHART_VERSION }}" ]]; then
          echo "WARNING: No previous chart version found, proceeding anyway"
          echo "::set-output name=PACKAGE_CHARTS::true"
        elif version_gt ${{ needs.check-chart-diffs.outputs.chart_version }} ${{ env.PROD_CHART_VERSION }}; then
          echo "${{ needs.check-chart-diffs.outputs.chart_version }} is greater than ${{ env.PROD_CHART_VERSION }}"
          echo "::set-output name=PACKAGE_CHARTS::true"
        else
          echo "Chart semantic version in pull request must be greater than main branch!"
          exit 1
        fi